### PR TITLE
Add Code of Conduct to pulpproject.org

### PR DESCRIPTION
**Pull request by CodeHeeler**
Adding the text of our CoC to /conduct/ and linking to it from nav

fixes #3599
https://pulp.plan.io/issues/3599

### CODE REVIEW

**Comment by CodeHeeler** [comment]
So this is WIP awaiting one bit of feedback:

On line 610 of customstyles.css there is the following:
h3 {color: #ED1951; font-weight:normal; font-size:130%;}

This is causing the subheadings on the Code of Conduct page to be red.  I haven't been able to find this used on any pages, but before making any changes, wanted to see if anyone knew why we had these as red in the first place.

**Comment by CodeHeeler** [comment]
Also, as a note of style/usability, with the topnav getting longer, do we wish to move to having a drop down menu of maybe "Community" that includes some subset of pages, possibly the Blog, Get Involved, Code of Conduct or whatever we feel works?  Happy to leave it as is if this isn't urgently desired.

**Comment by dkliban** [comment]
I think you should try changing it from red to black or whatever colors makes the most sense. This website was forked from an existing template so the color chice was probably made before any of us got involved. 

Let's keep the menu as is, but we should consider making a separate PR to change it.

**Comment by CodeHeeler** [comment]
For reference, it was in theme-blue.css, same h3 change from red to black, that solved it.

**Review by dkliban — APPROVED** [review]

**Pull request merged**
