### PR TITLE
Community manager announcement

### PR DESCRIPTION
**Pull request by melcorr**

### CODE REVIEW

**Review by RCMariko — APPROVED** [review]
Looks great! Love the call for feedback and the tone it sets - hope we get some suggestions. (only minor nit is that I think it's "roadmap" not "road map"?)

**Comment by melcorr** [comment]
> (only minor nit is that I think it's "roadmap" not "road map"?)

That was my text editor! Thank you for the catch :)

**Comment by ipanova** [comment]
@melcorr this all looks great, the only question i have is - why there are 2 identical blogposts with different dates?

**Comment by melcorr** [comment]
> @melcorr this all looks great, the only question i have is - why there are 2 identical blogposts with different dates?

Silly me. I moved the file to update the date... because I started writing this last week and got nowhere with it.. I will fix this now.

**Pull request merged**
