### PR TITLE
Add homepage title

### PR DESCRIPTION
**Pull request by rayanimesh**
Add missing homepage title on website pulpproject.org.

pulp-missing-homepage-title

### CODE REVIEW

**Comment by bmbouter** [comment]
Thank you for the PR. I've wanted this fixed for a while but this fix has a negative side-effect that the text 'Pulp' is shown in large font on the homepage. See this pic.

image

Would you be willing to adjust [the logic here](https://github.com/pulp/pulpproject.org/blob/gh-pages/_layouts/page.html#L6) to only have the title show if it's not on the homepage?

In terms of testing your changes, if you push your branch head to gh-pages in your fork you can see it rendered with github if you enable pages for your forked repo here:  https://rayanimesh.github.io/pulpproject.org/

**Comment by rayanimesh** [comment]
> Would you be willing to adjust the logic here to only have the title show if it's not on the homepage?

Done.  

Tested on localhost. PFA screenshots for the same. Also pushed it to `gh-pages`.  https://rayanimesh.github.io/pulpproject.org/

pulp-updated

---

pulp updated 2

**Comment by bmbouter** [comment]
Thanks @rayanimesh  👍 Do you have a twitter handle that I can tweet a thank you to?

**Comment by rayanimesh** [comment]
My twitter is https://twitter.com/animesh_ray.

**Comment by bmbouter** [comment]
@rayanimesh I tweeted it [here](https://twitter.com/pulpproj/status/864849085752369152). We like to send a shirt to all first-time contributors. If you send me your mailing address and size, I can ship one to you. You can email the info to bbouters@redhat.com or private message it to me; I'm bmbouter on freenode.

Also would you have any interest in picking up one of the other [website issues](https://github.com/pulp/pulpproject.org/issues/)? The Pulp community would benefit from any of those issues being fixed. Let me know if you have any questions about them. Thanks again!

**Comment by rayanimesh** [comment]
Thanks for the appereciation @bmbouter :smile:. Emailing you my mailing address with subject `Animesh Ray | Mailing Address`.

I will go through other website issues and see how can I help.

**Pull request merged**
