### PR TITLE
Add back the Docs header.

### PR DESCRIPTION
**Pull request by melcorr**
* Pulp 3 plugin doc links

### CODE REVIEW

**Comment by daviddavis** [comment]
This looks great. I would probably organize the docs page a little differently though:

```
# Pulp 3

## Pulpcore Documentation

* Latest: [docs.pulpproject.org](http://docs.pulpproject.org).
* Nightly: [http://docs.pulpproject.org/en/master/nightly/](http://docs.pulpproject.org/en/master/nightly/).
* Ansible installer: [https://pulp-installer.readthedocs.io/en/latest/](https://pulp-installer.readthedocs.io/en/latest/).

## Pulp 3 Content Plugin Documentation

* [RPM plugin](https://pulp-rpm.readthedocs.io/en/latest/)
* [File plugin](https://pulp-file.readthedocs.io/en/latest/)
* [Container plugin](https://pulp-container.readthedocs.io/en/latest/)
* [Ansible plugin](https://pulp-ansible.readthedocs.io/en/latest/)
* [Debian plugin](https://pulp-deb.readthedocs.io/en/latest/)
* [Python plugin](https://pulp-python.readthedocs.io/en/latest/)
* [Chef Cookbook plugin](https://github.com/gmbnomis/pulp_cookbook/blob/master/README.rst)
* [Maven plugin](https://github.com/pulp/pulp_maven/blob/master/README.rst)
* [RubyGem plugin](https://github.com/pulp/pulp_gem/blob/master/README.rst)
* [Ansible GalaxyNG plugin](https://github.com/ansible/galaxy_ng/blob/master/README.md)

## Other plugins

* [Certguard plugin](https://pulp-certguard.readthedocs.io/en/latest/)
* [Migration Plugin](https://pulp-2to3-migration.readthedocs.io/en/latest/index.html)


# Pulp 2

See the latest Pulp 2 docs at [docs.pulpproject.org/en/2.21/](http://docs.pulpproject.org/en/2.21/)

## Older

* [Pulp 2.20](http://docs.pulpproject.org/en/2.20/)
* [Pulp 2.19](http://docs.pulpproject.org/en/2.19/)
* [Pulp 2.18](http://docs.pulpproject.org/en/2.18/)
* [Pulp 2.17](http://docs.pulpproject.org/en/2.17/)
* [Pulp 2.16](http://docs.pulpproject.org/en/2.16/)
* [Pulp 2.15](http://docs.pulpproject.org/en/2.15/)
* [Pulp 2.14](http://docs.pulpproject.org/en/2.14/)
* [Pulp 2.13](http://docs.pulpproject.org/en/2.13/)
* [Pulp 2.12](http://docs.pulpproject.org/en/2.12/)
* [Pulp 2.11](http://docs.pulpproject.org/en/2.11/)
* [Pulp 2.10](http://docs.pulpproject.org/en/2.10/)
* [Pulp 2.9](http://docs.pulpproject.org/en/2.9/)
* [Pulp 2.8](http://docs.pulpproject.org/en/2.8/)
* [Pulp 2.7](http://docs.pulpproject.org/en/2.7/)
* [Pulp 2.6](http://docs.pulpproject.org/en/2.6/)

## Related Projects

* [Nectar](http://nectar.readthedocs.org/en/latest/)
* [Okaara](http://okaara.readthedocs.org/en/latest/)
```

**Comment by melcorr** [comment]
I bow to your superior knowledge and will implement this on Monday :)
Thank you!

**Comment by ipanova** [comment]
@daviddavis @melcorr any reason we are displaying docs for such old releases like 2.6?
what about keeping latest release and last -2 releases

**Comment by daviddavis** [comment]
@ipanova that sounds good to me.

**Comment by melcorr** [comment]
@ipanova  

Thanks, Ina. I'll remove those now.

**Pull request merged**
