### PR TITLE
Add Pulp Discourse

### PR DESCRIPTION
**Pull request by melcorr**

### CODE REVIEW

**Review by daviddavis — APPROVED** [review]
I'm a bit torn. Maybe we should indicate that this discourse instance is a trial instance. OTOH, I personally very much want to see us move to Discourse.

**Comment by melcorr** [comment]
> I'm a bit torn. Maybe we should indicate that this discourse instance is a trial instance. OTOH, I personally very much want to see us move to Discourse.

In the email to the list, I stressed the trial part of this. I can do that here too. Seems reasonable.

**Comment by daviddavis** [comment]
Ok, up to you.

**Review by daviddavis — APPROVED** [review]

**Comment by melcorr** [comment]
Thanks for your review!

**Pull request merged**
