### PR TITLE
Add release announcement for Pulpcore 3.15

### PR DESCRIPTION
**Pull request by melcorr**
Preview here: 

https://melcorr.github.io/pulpproject.org/2021/08/28/pulpcore-3.15-is-generally-available/

### CODE REVIEW

**Review by mdellweg — APPROVED** [review]

**Review by fao89 — COMMENTED** [review]
I think we need to mention @dkliban PR
https://github.com/pulp/pulpcore/pull/1553
Not sure if here is the right place, maybe a separate blog post for developers?

**Comment by melcorr** [comment]
> I think we need to mention @dkliban PR
> [pulp/pulpcore#1553](https://github.com/pulp/pulpcore/pull/1553)
> Not sure if here is the right place, maybe a separate blog post for developers?

I have, hand on heart, no idea what is going on in that PR. 
If we need to put it in the announcement, I would appreciate someone helping me a bit. 
I used towncrier to gather merged work and build the announcement from that. This PR looks like it was closed so therefore never got into my draft  !

**Comment by mdellweg** [comment]
> > I think we need to mention @dkliban PR
> > [pulp/pulpcore#1553](https://github.com/pulp/pulpcore/pull/1553)
> > Not sure if here is the right place, maybe a separate blog post for developers?
> 
> I have, hand on heart, no idea what is going on in that PR.
> If we need to put it in the announcement, I would appreciate someone helping me a bit.
> I used towncrier to gather merged work and build the announcement from that. This PR looks like it was closed so therefore never got into my draft !

I just mentioned it in https://discourse.pulpproject.org/t/plugin-adjustments-for-3-15/94 maybe that's enough.

**Comment by fao89** [comment]
> 
> I just mentioned it in https://discourse.pulpproject.org/t/plugin-adjustments-for-3-15/94 maybe that's enough.

+1,  thank you @mdellweg 

>
> I have, hand on heart, no idea what is going on in that PR.

@melcorr sorry for the confusion I created

**Comment by melcorr** [comment]
> > I just mentioned it in https://discourse.pulpproject.org/t/plugin-adjustments-for-3-15/94 maybe that's enough.
> 
> +1, thank you @mdellweg
> 
> > I have, hand on heart, no idea what is going on in that PR.
> 
> @melcorr sorry for the confusion I created

Not at all :)

**Comment by melcorr** [comment]
I will add @mdellweg's post as a link

**Review by mdellweg — APPROVED** [review]

**Review by fao89 — APPROVED** [review]

**Pull request merged**
