### PR TITLE
Update to new triage logs location

### PR DESCRIPTION
**Pull request by tehsmyers**
I ran this through jekyll and it seemed to be fine. I was tempted to mess with the link and do dynamic things with the date component, but then just opted to fix this specific issue and leave fun dynamicism for another time.

### CODE REVIEW

**Comment by bmbouter** [comment]
Both the old url and the new url show me logs. Is the old url broken somehow?

**Comment by tehsmyers** [comment]
I was planning to leave it in place as long as the site still pointed to it. Once this gets merged and jekyll regens, the old location will be deleted.

**Comment by tehsmyers** [comment]
Oh, and yes, the old URL is missing a required path component that we need to let pulpbot generate correct URLs to the logs.

**Comment by bmbouter** [comment]
@seandst Thanks for this PR!

**Pull request merged**
